import { entriesForPeriod, futureValue, parseDate, retirementDate, sortEntries, summary, yearsBetween } from "../domain/calculations.js";
const money = new Intl.NumberFormat("da-DK", { style: "currency", currency: "DKK", maximumFractionDigits: 0 });
const num = new Intl.NumberFormat("da-DK", { maximumFractionDigits: 1 });
const axisMoney = (value) => `${num.format(value / 1_000_000)} mio.`;
const dateFormat = new Intl.DateTimeFormat("da-DK", { day: "numeric", month: "short", year: "numeric" });
export const formatMoney = (value) => money.format(value);
export const formatDate = (value) => dateFormat.format(typeof value === "string" ? parseDate(value) : value);
export const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char]));
const periodButtons = (active = "all") => `<div class="segmented" data-periods>${[["1y","1 år"],["2y","2 år"],["3y","3 år"],["4y","4 år"],["5y","5 år"],["all","Alle"]].map(([id,label]) => `<button type="button" data-period="${id}" aria-pressed="${id === active}">${label}</button>`).join("")}</div>`;
function chart(entries, rate, retire, showForecast = true) {
  if (!entries.length) return `<div class="empty-chart"><strong>Din kurve begynder her</strong><span>Tilføj din første registrering for at se udviklingen.</span></div>`;
  const first = entries[0], last = entries.at(-1), now = new Date();
  const end = retire > now ? retire : new Date(now.getFullYear() + 10, now.getMonth(), now.getDate());
  const all = entries.map((e) => ({ date: parseDate(e.date), value: e.balance, actual: true }));
  if (showForecast) for (let i=1;i<=36;i++) { const fraction=i/36, date=new Date(now.getTime()+(end-now)*fraction); all.push({date,value:futureValue(last.balance,rate,yearsBetween(now,date))}); }
  const minT=Math.min(...all.map(p=>p.date)), maxT=Math.max(...all.map(p=>p.date)), minV=Math.min(...all.map(p=>p.value))*.94, maxV=Math.max(...all.map(p=>p.value))*1.04;
  const x=(d)=>105+(Number(d)-minT)/Math.max(1,maxT-minT)*615, y=(v)=>244-(v-minV)/Math.max(1,maxV-minV)*204;
  const actual=entries.map((e,i)=>`${i?"L":"M"}${x(parseDate(e.date))},${y(e.balance)}`).join(" ");
  const forecast=showForecast?[{date:now,value:last.balance},...all.filter(p=>!p.actual)].map((p,i)=>`${i?"L":"M"}${x(p.date)},${y(p.value)}`).join(" "):"";
  const gridLines=[40,90,140,190,240].map((line,index)=>{const value=maxV-(maxV-minV)*(index/4);return `<line x1="105" x2="720" y1="${line}" y2="${line}" class="grid"></line><text x="96" y="${line+4}" text-anchor="end">${axisMoney(value)}</text>`;}).join("");
  return `<div class="chart-wrap"><svg class="chart" viewBox="0 0 746 280" role="img" aria-label="Seneste opsparing ${money.format(last.balance)}.${showForecast?` Prognose ${num.format(rate)} procent.`:""}">${gridLines}<path d="${actual}" class="actual-line"></path>${showForecast?`<path d="${forecast}" class="future-line"></path>`:""}<circle cx="${x(parseDate(last.date))}" cy="${y(last.balance)}" r="6" class="dot"></circle><text x="105" y="270">${formatDate(new Date(minT))}</text><text x="720" y="270" text-anchor="end">${formatDate(new Date(maxT))}</text></svg><div class="legend"><span><i class="actual-key"></i>Faktisk</span>${showForecast?`<span><i class="future-key"></i>Prognose (${num.format(rate)} %)</span>`:""}</div></div>`;
}
export function dashboardScreen(entries, settings, period = "all") {
  const sorted=sortEntries(entries), last=sorted.at(-1), previous=sorted.at(-2), filtered=entriesForPeriod(sorted,period), stats=summary(filtered), yearStats=summary(entriesForPeriod(sorted,"ytd")), retire=retirementDate(settings.birthDate,settings.retirementAge), years=yearsBetween(new Date(),retire), atRetirement=last?futureValue(last.balance,settings.growthRate,years):0, delta=last&&previous?last.balance-previous.balance:null;
  return `<section class="hero"><div class="hero-top"><div><p class="eyebrow">DIN PENSIONSOPSPARING</p><p class="balance">${last?money.format(last.balance):"—"}</p><p class="muted">${last?`Opdateret ${formatDate(last.date)}`:"Ingen registreringer endnu"}</p></div><button class="primary add" data-add>＋ Tilføj</button></div>${last?`<div class="hero-stats"><div><span>Siden sidst</span><strong>${delta===null?"—":`${delta>=0?"+":""}${money.format(delta)}`}</strong></div><div><span>Ændring</span><strong>${delta===null||!previous.balance?"—":`${delta>=0?"+":""}${num.format(delta/previous.balance*100)} %`}</strong></div><div><span>Tilvækst i år</span><strong>${yearStats.percent==null?"—":`${yearStats.percent>=0?"+":""}${num.format(yearStats.percent)} %`}</strong></div><div><span>Ved pension</span><strong>${money.format(atRetirement)}</strong></div></div>`:""}</section><section class="section-head"><div><p class="eyebrow">UDVIKLING</p><h2>Din opsparing over tid</h2></div>${stats.amount!==undefined?`<div class="period-change"><span>Valgt periode</span><strong>${stats.amount>=0?"+":""}${money.format(stats.amount)}</strong></div>`:""}</section>${periodButtons(period)}<section class="card chart-card">${chart(filtered,settings.growthRate,retire,period==="all")}</section><section class="section-head"><div><p class="eyebrow">PROGNOSE</p><h2>Hvis pengene vokser ${num.format(settings.growthRate)} % årligt</h2></div></section>${last?`<div class="forecast-grid">${[1,2,3,5,10].map(y=>`<article class="card forecast"><span>Om ${y} år</span><strong>${money.format(futureValue(last.balance,settings.growthRate,y))}</strong><small>+${money.format(futureValue(last.balance,settings.growthRate,y)-last.balance)}</small></article>`).join("")}<article class="card forecast featured"><span>Ved pension · ${formatDate(retire)}</span><strong>${money.format(atRetirement)}</strong><small>${years>0?`${num.format(years)} år tilbage`:"Pensionsdatoen er passeret"}</small></article></div>`:`<div class="card empty-copy">Tilføj en registrering for at se prognosen.</div>`}<p class="disclaimer">Prognoserne er illustrative regneeksempler baseret på en konstant vækstrate uden fremtidige indbetalinger, skat, gebyrer eller inflation. Appen yder ikke finansiel rådgivning.</p>`;
}
export function historyScreen(entries, period="all") {
  const visible=entriesForPeriod(entries,period).reverse();
  return `<section class="page-title"><div><p class="eyebrow">ALLE REGISTRERINGER</p><h1>Historik</h1><p>Se og vedligehold dine opsparingsdata.</p></div><button class="primary add" data-add>＋ Tilføj</button></section>${periodButtons(period)}<section class="history-list">${visible.length?visible.map(e=>`<article class="card history-row"><div class="date-badge"><strong>${parseDate(e.date).getDate()}</strong><span>${new Intl.DateTimeFormat("da-DK",{month:"short"}).format(parseDate(e.date))}</span></div><div class="history-main"><strong>${money.format(e.balance)}</strong><span>${e.contribution!=null?`Indbetaling ${money.format(e.contribution)}`:"Ingen indbetaling angivet"}${e.note?` · ${escapeHtml(e.note)}`:""}</span></div><div class="row-actions"><button data-edit="${e.id}">Rediger</button><button class="danger-text" data-delete="${e.id}">Slet</button></div></article>`).join(""):`<div class="card empty-copy">Ingen registreringer i denne periode.</div>`}</section>`;
}
export function settingsScreen(settings) {
  const retire=retirementDate(settings.birthDate,settings.retirementAge);
  return `<section class="page-title"><div><p class="eyebrow">TILPAS APPEN</p><h1>Indstillinger</h1><p>Dine valg og data gemmes kun på denne enhed.</p></div></section><div class="settings-grid"><section class="card settings-card"><h2>Prognose</h2><label>Årlig vækstrate<div class="suffix"><input data-setting="growthRate" type="number" min="-20" max="30" step="0.1" value="${settings.growthRate}"><span>%</span></div></label><p class="hint">Standard er 5 %.</p><label>Pensionsalder<div class="suffix"><input data-setting="retirementAge" type="number" min="50" max="100" value="${settings.retirementAge}"><span>år</span></div></label><p class="hint">Pensionsdato: ${formatDate(retire)}</p></section><section class="card settings-card"><h2>Profil og udseende</h2><label>Fødselsdato<input data-setting="birthDate" type="date" value="${settings.birthDate}"></label><label>Tema<select data-setting="theme"><option value="auto" ${settings.theme==="auto"?"selected":""}>Følg enheden</option><option value="light" ${settings.theme==="light"?"selected":""}>Lyst</option><option value="dark" ${settings.theme==="dark"?"selected":""}>Mørkt</option></select></label></section><section class="card settings-card"><h2>Sikkerhedskopi</h2><p>Importér din historik eller hent en sikkerhedskopi.</p><div class="button-stack"><button class="secondary" data-export>Eksportér sikkerhedskopi</button><label class="check"><input type="checkbox" data-merge checked> Sammenflet ved import</label><button class="secondary" data-import>Importér sikkerhedskopi</button><input hidden type="file" accept="application/json" data-file></div></section><section class="card settings-card"><h2>Data på enheden</h2><p>Data kan forsvinde, hvis browserdata slettes.</p><button class="danger" data-clear>Slet alle registreringer</button></section></div>`;
}
